/**
 * Auto-generated migration map for admin-console
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration admin-console
 */

import * as Generated from '@autional/shared/generated/api';
import type {
	CloneTemplateToLocaleRequest as GeneratedCloneTemplateToLocaleRequest,
	CreateTemplateRequest as GeneratedCreateTemplateRequest,
	ExchangePointsRequest,
	TransferPointsRequest,
} from '@autional/shared/generated/types';
import { apiClient } from '@autional/shared';

export const getUsers = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminUsers(params);
export const getUser = (userId: string, _signal?: AbortSignal) =>
	Generated.adminUsersByUsers(userId);
export const createUser = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminUsersPost(data);
export const updateUser = (userId: string, data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminUsersByUsersPut(userId, data);
export const deleteUser = (userId: string, _signal?: AbortSignal) =>
	Generated.adminUsersByUsersDelete(userId);
export const updateUserStatus = Generated.adminUsersStatusByUsersPut;
export const unlockUser = Generated.adminUsersAccountUnlocksByUsersPost;
export const resetUserPassword = Generated.adminUsersPasswordResetsByUsersPost;
export const resetUserMFA = Generated.adminMfaResetByResetDelete;
export const getActiveSessionCount = (_signal?: AbortSignal) =>
	Generated.adminSessionsActiveCount();
export const changePassword = Generated.authMePasswordPut;
export const getUserRoles = Generated.adminUsersRolesByUsers;
export const assignUserRoles = Generated.adminUsersRolesByUsersPost;
export const removeUserRoles = Generated.adminUsersRolesByUsersDelete;
export const getUserPermissions = Generated.adminUsersPermissionsByUsers;
export const getUserLoginHistories = Generated.adminUsersLoginHistoriesByUsers;
export const getRoles = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminRoles(params);
export const getRole = (roleId: string, _signal?: AbortSignal) =>
	Generated.adminRolesByRoles(roleId);
export const createRole = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminRolesPost(data);
export const updateRole = (roleId: string, data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminRolesByRolesPut(roleId, data);
export const deleteRole = (roleId: string, _signal?: AbortSignal) =>
	Generated.adminRolesByRolesDelete(roleId);
export const getRolePermissions = (roleId: string, _signal?: AbortSignal) =>
	Generated.adminRolesPermissionsByRoles(roleId);
export const assignRolePermissions = (
	roleId: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminRolesPermissionsByRolesPost(roleId, data);
export const removeRolePermissions = (
	roleId: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminRolesPermissionsByRolesDelete(roleId, data);
export const getPermissions = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminPermissions(params);
export const createPermission = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminPermissionsPost(data);
export const updatePermission = (
	permissionId: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminPermissionsByPermissionsPut(permissionId, data);
export const deletePermission = (permissionId: string, _signal?: AbortSignal) =>
	Generated.adminPermissionsByPermissionsDelete(permissionId);
export const getDepartments = Generated.adminTenantsDepartmentsByTenants;
export const createDepartment = Generated.adminTenantsDepartmentsByTenantsPost;
export const updateDepartment = Generated.adminTenantsDepartmentsByTenantsByDepartmentsPut;
export const deleteDepartment = Generated.adminTenantsDepartmentsByTenantsByDepartmentsDelete;
export const getMembers = Generated.adminTenantsMembersByTenants;
export const inviteMember = Generated.adminTenantsMembersInviteByTenantsPost;
export const getSessions = Generated.adminSessions;
export const deleteSession = Generated.sessionsBySessionsDelete;
export const getAuditLogs = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditLogs(params);
export const getAuditStats = (_signal?: AbortSignal) => Generated.adminAuditStats();
export const verifyAuditChain = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditVerificationsPost(data);
export const getAuditLogDetail = (id: string, _signal?: AbortSignal) =>
	Generated.adminAuditLogsByLogs(id);
export const exportAuditLogs = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditExportPost(data);
export const getTenantBranding = Generated.adminTenantsBrandingByTenants;
export const updateTenantBranding = Generated.adminTenantsBrandingByTenantsPut;
export const getDataClassification = (tenantId: string) =>
	Generated.adminTenantsDataClassificationByTenants(tenantId);
export const updateDataClassification = (tenantId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsDataClassificationByTenantsPost(tenantId, data);
export const getApplications = Generated.adminTenantsApplicationsByTenants;
// A-43：租户自定义应用类型（表单 Select 选项 + 列表 type 回显名称）
export const getAppTypes = Generated.adminTenantsAppTypesByTenants;
export const createApplication = Generated.adminTenantsApplicationsByTenantsPost;
export const updateApplication = Generated.adminTenantsApplicationsByTenantsByApplicationsPut;
export const deleteApplication = Generated.adminTenantsApplicationsByTenantsByApplicationsDelete;
export const suspendApplication =
	Generated.adminTenantsApplicationsSuspendByTenantsByApplicationsPost;
export const activateApplication =
	Generated.adminTenantsApplicationsActivateByTenantsByApplicationsPost;
export const updateMember = Generated.adminTenantsMembersByTenantsByMembersPut;
export const removeMember = Generated.adminTenantsMembersByTenantsByMembersDelete;
export const getPasswordPolicy = Generated.adminSecurityPasswordPolicy;
export const updatePasswordPolicy = Generated.adminSecurityPasswordPolicyPut;
export const getMFARiskPolicy = Generated.adminMfaRiskPolicy;
export const updateMFARiskPolicy = Generated.adminMfaRiskPolicyPut;
export const getSecurityPolicy = Generated.adminTenantsSecurityPolicyByTenants;
export const updateSecurityPolicy = Generated.adminTenantsSecurityPolicyByTenantsPut;
// 租户级认证策略（MFA 策略页 BUG-038：复用 tenant-service auth-policy 端点）
export const getAuthPolicy = Generated.adminTenantsAuthPolicyByTenants;
export const updateAuthPolicy = Generated.adminTenantsAuthPolicyByTenantsPut;
export const getIdentityProviders = Generated.adminIdentityProviders;
export const createIdentityProvider = Generated.adminIdentityProvidersPost;
export const updateIdentityProvider = Generated.adminIdentityProvidersByIdentityProvidersPut;
export const deleteIdentityProvider = Generated.adminIdentityProvidersByIdentityProvidersDelete;
export const testIdentityProvider = Generated.adminIdentityProvidersTestByIdentityProvidersPost;
// SAML IdP (saml-service) — 供 /identity-providers 页聚合展示 (authms_saml.saml_providers)
export const getSamlProviders = Generated.adminSamlProviders;
export const createSamlProvider = Generated.adminSamlProvidersPost;
export const updateSamlProvider = Generated.adminSamlProvidersByProvidersPut;
export const deleteSamlProvider = Generated.adminSamlProvidersByProvidersDelete;

// LDAP Directory
export const testLdapConnection = (data: { directoryName: string }) =>
	Generated.adminLdapTestConnectionPost(data);
export const getLdapHealth = () => Generated.adminLdapHealth();

export const getWebhooks = Generated.adminTenantsWebhooksByTenants;
export const createWebhook = Generated.adminTenantsWebhooksByTenantsPost;
export const updateWebhook = Generated.adminTenantsWebhooksByTenantsByWebhooksPut;
export const deleteWebhook = Generated.adminTenantsWebhooksByTenantsByWebhooksDelete;
export const testWebhook = Generated.adminTenantsWebhooksTestByTenantsByWebhooksPost;

// Audit: Export
export const getExportJobs = Generated.adminAuditExportJobs;
export const downloadExportJob = Generated.adminAuditExportDownloadByExport;

// Audit: Hash Chain & Merkle
export const getHashChain = Generated.adminAuditHashchainByHashchain;
export const getMerkleProof = Generated.adminAuditMerkleProof;
export const getVerifications = Generated.adminAuditVerifications;

// Audit: Archive
export const getArchiveStatus = Generated.adminAuditArchiveStatus;
export const triggerArchive = Generated.adminAuditArchivePost;

// Audit: Alerts
export const getAlerts = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditAlerts(params);
// A-205（W1e）：getAlertById 死包装删（useAlertDetail 死链同步删；grep 零消费）
export const updateAlertStatus = (id: string, data: any, _signal?: AbortSignal) =>
	Generated.adminAuditAlertsStatusByAlertsPut(id, data);
export const assignAlert = (id: string, data: any, _signal?: AbortSignal) =>
	Generated.adminAuditAlertsAssignByAlertsPost(id, data);

// Audit: Anomalies
export const getAnomalies = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditAnomalies(params);
// A-214（W1e）：getAnomalyById 死包装删（useAnomalyDetail 死链同步删；grep 零消费）
export const updateAnomalyStatus = (id: string, data: any, _signal?: AbortSignal) =>
	Generated.adminAuditAnomaliesStatusByAnomaliesPut(id, data);
export const assignAnomaly = (id: string, data: any, _signal?: AbortSignal) =>
	Generated.adminAuditAnomaliesAssignByAnomaliesPost(id, data);
export const addAnomalyComment = (
	id: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminAuditAnomaliesCommentByAnomaliesPost(id, data);
export const getAnomalyTimeline = (id: string, _signal?: AbortSignal) =>
	Generated.adminAuditAnomaliesTimelineByAnomalies(id);
export const getRelatedAnomalies = (id: string, _signal?: AbortSignal) =>
	Generated.adminAuditAnomaliesRelatedByAnomalies(id);
export const detectAnomalies = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAuditAnomaliesDetectPost(data);
export const linkAnomalyToCase = (
	id: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminAuditAnomaliesLinkByAnomaliesPost(id, data);

// Audit: SIEM Connectors
export const getSIEMConnectors = Generated.adminAuditSiemConnectors;
export const createSIEMConnector = Generated.adminAuditSiemConnectorsPost;
export const updateSIEMConnector = Generated.adminAuditSiemConnectorsByConnectorsPut;
export const deleteSIEMConnector = Generated.adminAuditSiemConnectorsByConnectorsDelete;
export const testSIEMConnector = Generated.adminAuditSiemConnectorsTestByConnectorsPost;

// Audit: Retention
export const getRetentionPolicy = Generated.adminAuditRetentionPolicy;
export const saveRetentionPolicy = Generated.adminAuditRetentionPolicyPut;

// Audit: Financial Events
export const getWalletEvents = Generated.adminAuditWalletEvents;
export const getBillingEvents = Generated.adminAuditBillingEvents;
export const getPaymentEvents = Generated.adminAuditPaymentEvents;

// Audit: Hash Chain & Merkle (continued)
export const getHashChainVerifyByDate = Generated.adminAuditHashchainVerifyByDateByHashchain;
export const getMerkleRoot = Generated.adminAuditMerkleRoot;
export const getMerkleProofs = Generated.adminAuditMerkleProofsPost;

// Audit: Export (continued)
export const getExportJobStatus = Generated.adminAuditExportStatusByExport;

// Audit: Reports
export const getSecurityReport = Generated.adminAuditReportsSecurity;
export const getComplianceReport = Generated.adminAuditReportsCompliance;

// Audit: SSE Stream
export const getAuditStream = Generated.adminAuditStream;

// Audit: Compliance
export const getPIAs = Generated.adminAuditCompliancePias;
export const createPIA = Generated.adminAuditCompliancePiasPost;
export const getBreaches = Generated.adminAuditComplianceBreaches;
export const createBreach = Generated.adminAuditComplianceBreachesPost;
export const getDataClassifications = Generated.adminAuditComplianceDataClassifications;
export const createDataClassification = Generated.adminAuditComplianceDataClassificationsPost;
export const getCrossBorderTransfers = Generated.adminAuditComplianceCrossBorder;
export const createCrossBorderTransfer = Generated.adminAuditComplianceCrossBorderPost;
export const getAIDecisions = Generated.adminAuditComplianceAiDecisions;
export const createAIDecision = Generated.adminAuditComplianceAiDecisionsPost;
export const getCleanupRecords = Generated.adminAuditComplianceCleanupRecords;
export const getCleanupRecord = Generated.adminAuditComplianceCleanupRecordsByCleanupRecords;
export const createCleanupRecord = Generated.adminAuditComplianceCleanupRecordsPost;
export const getSODRules = Generated.adminAuditComplianceSodRules;
export const getRoleActions = Generated.adminAuditComplianceRoleActions;

// Audit: Tenant Config
export const getTenantConfig = Generated.adminAuditTenantConfig;
export const saveTenantConfig = Generated.adminAuditTenantConfigPut;

// Billing: Subscription
// U316：读取族改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）
export const getBillingSubscription = (tenantId: string, _signal?: AbortSignal) =>
	Generated.adminBillingSubscriptionBySubscription(tenantId);
export const changeBillingPlan = Generated.adminBillingSubscriptionChangePlanBySubscriptionPost;
export const getBillingUsage = (tenantId: string, _signal?: AbortSignal) =>
	Generated.adminBillingUsageCurrentByUsage(tenantId);
export const getBillingStatistics = (tenantId: string, _signal?: AbortSignal) =>
	Generated.adminBillingStatisticsByStatistics(tenantId);
export const getBillingRecords = (tenantId: string, _signal?: AbortSignal) =>
	Generated.adminBillingRecordsByRecords(tenantId);
export const getInvoice = Generated.billingInvoiceByInvoice;
export const exportInvoice = Generated.billingInvoiceExportByInvoice;

// Billing: Plans CRUD
export const getBillingPlans = Generated.adminBillingPlans;
export const createBillingPlan = Generated.adminBillingPlansPost;
export const updateBillingPlan = Generated.adminBillingPlansByPlansPut;
export const deleteBillingPlan = Generated.adminBillingPlansByPlansDelete;

// Billing: Payment Gateways
export const createPaymentGateway = Generated.adminBillingPaymentGatewaysPost;
export const updatePaymentGateway = Generated.adminBillingPaymentGatewaysByPaymentGatewaysPut;

// Billing: Credit Notes
export const createCreditNote = Generated.adminBillingInvoiceCreditNoteByInvoicePost;

// Billing: Refund Approvals
// A-409⑦：createRefundApproval/getRefundApproval 零消费（全仓 grep 仅定义自身）→ 裁剪
export const approveRefund = Generated.adminBillingRefundApprovalApproveByRefundApprovalPost;
export const rejectRefund = Generated.adminBillingRefundApprovalRejectByRefundApprovalPost;
export const executeRefund = Generated.adminBillingRefundApprovalExecuteByRefundApprovalPost;

// Billing: Tax & Revenue
export const getTaxExport = Generated.adminBillingTaxExport;
export const getRevenueAmortization = Generated.adminBillingRevenueAmortization;

// Billing: Dunning
export const getDunningSettings = Generated.adminBillingDunningSettingsByDunningSettings;
export const updateDunningSettings = Generated.adminBillingDunningSettingsByDunningSettingsPut;

// Billing: Subscription Management
export const updateSubscription = Generated.adminBillingSubscriptionBySubscriptionPut;
export const deleteSubscription = Generated.adminBillingSubscriptionBySubscriptionDelete;
export const extendTrial = Generated.adminBillingSubscriptionExtendTrialBySubscriptionPost;
export const cancelTrial = Generated.adminBillingSubscriptionCancelTrialBySubscriptionPost;
export const rollbackPlan = Generated.adminBillingSubscriptionRollbackPlanBySubscriptionPost;

// Billing: App Pricing
export const getAppPricing = Generated.adminBillingSubscriptionAppsPricingBySubscriptionByApps;
export const configureAppPricing =
	Generated.adminBillingSubscriptionAppsPricingBySubscriptionByAppsPost;

// Billing: Balance/Credit
export const getBillingBalance = Generated.billingBalance;
// U316：控制台改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）。
// admin 双生端点尚未进 generated（待下轮 swagger 重生成），此处自写（apiClient 直调 admin 路径）。
export const getCreditBalance = async (tenantId: string, _signal?: AbortSignal) => {
	const res = await apiClient.get(`/billing/api/v1/admin/billing/credit-balance/${tenantId}`, {
		signal: _signal,
	});
	return res.data;
};
export const getCreditTransactions = async (
	tenantId: string,
	params?: { page?: number; page_size?: number; source?: string },
	_signal?: AbortSignal,
) => {
	const res = await apiClient.get(`/billing/api/v1/admin/billing/credit-transactions/${tenantId}`, {
		params,
		signal: _signal,
	});
	return res.data;
};

// Billing: Public Plans
export const getPublicBillingPlans = Generated.billingPlans;

export const getDSARs = Generated.adminComplianceGdprDsar;
export const updateDSAR = Generated.adminComplianceGdprDsarByDsarPut;
// A-234（TASK-AB2-26）：擦除四映射归位。旧 `executeErasure` 误接**创建端点**
// （adminComplianceGdprRightToErasurePost = POST /right-to-erasure）且调用方把 id 字符串当 body
// ⇒ 必败 400；真执行端点 = POST /right-to-erasure/{erasure_id}/execute（路径参数，无 body）。
export const getErasures = Generated.adminComplianceGdprRightToErasure;
export const createErasure = Generated.adminComplianceGdprRightToErasurePost;
export const getErasure = Generated.adminComplianceGdprRightToErasureByRightToErasure;
export const executeErasure = Generated.adminComplianceGdprRightToErasureExecuteByRightToErasurePost;
export const getRetentionPolicies = Generated.adminComplianceRetentionPolicies;
export const getComplianceSODRules = Generated.adminComplianceSodRules;
export const getISOControls = Generated.adminComplianceIso27001Controls;
// U316：存储读写改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）。
// 上传/下载生成函数无 multipart/blob 能力，此处自写（apiClient 直调 admin 路径）。
export const getFiles = Generated.adminStorageFiles;
export const uploadFile = (formData: FormData, _signal?: AbortSignal) =>
	apiClient.post('/storage/api/v1/admin/storage/files', formData, {
		signal: _signal,
		headers: { 'Content-Type': 'multipart/form-data' },
	});
export const downloadFile = (fileId: string, _signal?: AbortSignal) =>
	apiClient.get(`/storage/api/v1/admin/storage/files/${fileId}/download`, {
		responseType: 'blob',
		signal: _signal,
	});
export const getStorageQuota = Generated.adminStorageQuota;
export const getStorageStats = Generated.adminStorageStats;
export const getStorageTrash = Generated.adminStorageTrash;
export const restoreTrashItem = Generated.adminStorageTrashRestoreByTrashPost;
export const deleteTrashItem = Generated.adminStorageTrashByTrashDelete;

// Wallet
export const getWalletSummary = Generated.adminWalletsTenantsSummaryByTenants;
export const getWalletTransactions = Generated.adminWalletsTenantsTransactionsByTenants;
export const getWalletDisputes = Generated.adminWalletsTenantsDisputesByTenants;
export const resolveDispute = Generated.adminWalletsTenantsDisputesResolveByTenantsByDisputesPost;
export const adjustWallet = Generated.adminWalletsUsersAdjustByUsersPost;

// Wallet: Coupons
export const updateCoupon = Generated.adminWalletsCouponsByCouponsPut;
export const deleteCoupon = Generated.adminWalletsCouponsByCouponsDelete;

// Wallet: Fraud Rules
export const getFraudRules = Generated.adminWalletsFraudRules;
export const updateFraudRules = Generated.adminWalletsFraudRulesPost;

// Wallet: Reconciliation
export const getReconciliation = Generated.adminWalletsReconciliation;

// Wallet: Batch Operations
export const batchFreezeWallets = Generated.adminWalletsBatchFreezePost;
export const batchUnfreezeWallets = Generated.adminWalletsBatchUnfreezePost;

// Wallet: Policy
export const getWalletPolicy = Generated.adminWalletsTenantsAppsPolicyByTenantsByApps;
export const updateWalletPolicy = Generated.adminWalletsTenantsAppsPolicyByTenantsByAppsPut;
// A-385⑥：DELETE /policy 端点接线（此前生成函数零消费）
export const deleteWalletPolicy = Generated.adminWalletsTenantsAppsPolicyByTenantsByAppsDelete;

// Wallet: App Summary
export const getWalletAppSummary = Generated.adminWalletsTenantsAppsSummaryByTenantsByApps;

// Wallet: CRUD
export const updateWallet = Generated.adminWalletsByWalletsPut;
export const deleteWallet = Generated.adminWalletsByWalletsDelete;

// Pay: Payments (admin plane, same body as user plane — U98)
export const listAdminPayments = Generated.adminPayments;
export const getAdminPayment = Generated.adminPaymentsByPayments;
export const getAdminPaymentReceipt = Generated.adminPaymentsReceiptByPayments;

// Pay: Admin Refunds (W2-01, A-352 — pay_refund_records 单源)
export const listAdminRefunds = Generated.adminRefunds;

// Pay: Admin Channels
export const listPayChannels = Generated.adminPaymentsChannels;
export const getPayChannel = Generated.adminPaymentsChannelsByChannels;
export const createPayChannel = Generated.adminPaymentsChannelsPost;
export const updatePayChannel = Generated.adminPaymentsChannelsByChannelsPut;
export const deletePayChannel = Generated.adminPaymentsChannelsByChannelsDelete;

// Pay: Admin Reconciliation
export const getPayReconciliation = Generated.adminPaymentsReconciliationHistory;
export const runPayReconciliation = Generated.adminPaymentsReconciliationPost;

// Verification: Admin
export const listVerifications = Generated.adminVerifications;
export const getVerificationStats = Generated.adminVerificationsStats;
export const overrideVerification = Generated.adminVerificationsOverrideByVerificationsPost;
// A-264（W1e）：导出 CSV + 人工复核双动作入口（导出返回原始 CSV 文本；拦截器对非信封实体透传）
export const exportVerifications = Generated.adminVerificationsExport;
export const manualReviewVerification = Generated.adminVerificationsManualReviewByVerificationsPost;
export const resolveVerificationReview = Generated.adminVerificationsResolveReviewByVerificationsPost;

// Points: Rules
export const getPointRules = Generated.adminPointRules;
export const createPointRule = Generated.adminPointRulesPost;
export const updatePointRule = Generated.adminPointRulesByPointRulesPut;
export const deletePointRule = Generated.adminPointRulesByPointRulesDelete;
export const testPointRule = Generated.adminPointRulesTestPost;

// Points: Accounts
export const getPointAccounts = Generated.adminPoints;
export const batchEarnPoints = Generated.adminPointsBatchEarnPost;
export const applyPointRule = Generated.adminPointsApplyRulePost;
export const adjustPoints = Generated.adminPointsAdjustByPointsPost;
export const expirePoints = Generated.adminPointsExpireByPointsPost;
export const freezePoints = Generated.adminPointsFreezeByPointsPost;
export const unfreezePoints = Generated.adminPointsUnfreezeByPointsPost;
export const updatePointAccountStatus = Generated.adminPointsStatusByPointsPut;

// Points: U316 控制台改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）。
// 交易列表复用现有 admin 生成函数 adminPointsTransactions；
// risk-score / transfer / exchange 的 admin 双生尚未进 generated（待下轮 swagger 重生成），此处自写。
export const getPointRiskScore = async (userId: string, _signal?: AbortSignal) => {
	const res = await apiClient.get(`/point/api/v1/admin/points/${userId}/risk-score`, {
		signal: _signal,
	});
	return res.data;
};
export const transferPoints = async (
	userId: string,
	data: TransferPointsRequest,
	_signal?: AbortSignal,
) => {
	const res = await apiClient.post(`/point/api/v1/admin/points/${userId}/transfer`, data, {
		signal: _signal,
	});
	return res.data;
};
export const exchangePoints = async (
	userId: string,
	data: ExchangePointsRequest,
	_signal?: AbortSignal,
) => {
	const res = await apiClient.post(`/point/api/v1/admin/points/${userId}/exchange`, data, {
		signal: _signal,
	});
	return res.data;
};

// U316：通知读取族改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）
export const getNotificationTemplates = Generated.adminNotificationsTemplates;
// A-164（TASK-AB1-26）：/available admin twin（TASK-AB1-08 后端已注册 adminRead twin），shared generated
// 尚未含 admin 路径（待下轮 swagger 重生成），此处自写（apiClient 直调 admin 路径；user 面同路径在 admin 平面 403）。
// 事件映射选择器数据源：条目含 code（列表端点 TemplateResponse 无 code = 旧数据源缺失的根因）。
export const getAvailableNotificationTemplates = async (_signal?: AbortSignal) => {
	const res = await apiClient.get('/notification/api/v1/admin/notifications/templates/available', {
		signal: _signal,
	});
	return res.data;
};
// A-151/A-155（TASK-AB1-25）：通知模板 create/clone 的 wire 契约以 service-notification 后端 DTO
// 实读为准（dto.go:312-320 CreateTemplateRequest：code/name/type/subject/content 必填；
// dto.go:902-907 CloneTemplateToLocaleRequest：target_locale 必填 + title/content 可选）。
// shared generated 的同名类型系 communication 面复用（create 多 channel 缺 type、clone 缺 title），
// 类型不实，此处按后端形状收口后再复用 generated 端点函数（URL 不复制；生成物刷新后可整体替换）。
export interface NotificationTemplateCreateRequest {
	code: string;
	name: string;
	type: string; // system | user | alert | reminder | promotion
	subject: string;
	content: string;
	format?: string;
	variables?: string[];
}

export interface NotificationTemplateCloneToLocaleRequest {
	targetLocale: string; // 拦截器转 target_locale
	title?: string;
	content?: string;
}

export const createNotificationTemplate = (data: NotificationTemplateCreateRequest) =>
	Generated.adminNotificationsTemplatesPost(data as unknown as GeneratedCreateTemplateRequest);
export const cloneNotificationTemplateToLocale = (
	id: string,
	data: NotificationTemplateCloneToLocaleRequest,
) =>
	Generated.adminNotificationsTemplatesCloneToLocaleByTemplatesPost(
		id,
		data as unknown as GeneratedCloneTemplateToLocaleRequest,
	);
export const updateNotificationTemplate = Generated.adminNotificationsTemplatesByTemplatesPut;
export const deleteNotificationTemplate = Generated.adminNotificationsTemplatesByTemplatesDelete;
export const testNotification = Generated.adminNotificationsTestPost;
export const getNotificationStats = Generated.adminNotificationsStats;
export const getEventMappings = Generated.adminNotificationsEventMappings;
export const getEventMapping = Generated.adminNotificationsEventMappingsByEventMappings;
export const createEventMapping = Generated.adminNotificationsEventMappingsPost;
export const updateEventMapping = Generated.adminNotificationsEventMappingsByEventMappingsPut;
export const deleteEventMapping = Generated.adminNotificationsEventMappingsByEventMappingsDelete;
export const getGlobalVariables = Generated.adminNotificationsGlobalVariables;
export const getGlobalVariable = Generated.adminNotificationsGlobalVariablesByGlobalVariables;
export const createGlobalVariable = Generated.adminNotificationsGlobalVariablesPost;
export const updateGlobalVariable = Generated.adminNotificationsGlobalVariablesByGlobalVariablesPut;
export const deleteGlobalVariable =
	Generated.adminNotificationsGlobalVariablesByGlobalVariablesDelete;
// U316：通信读取族改接 admin 面（user 面在 admin 平面被入口平面门禁拒 403）
export const getCommunicationTemplates = Generated.adminCommunicationTemplates;
export const getCommunicationTemplateStats = Generated.adminCommunicationTemplateStats;
// 无 admin 双生端点，且当前无页面消费；若日后接入需先补上游 admin 端点（U316 扫描遗留）
export const getCommunicationTemplatesAvailable = Generated.communicationTemplatesAvailable;
export const getCommunicationDashboard = Generated.adminCommunicationDashboard;
export const getCommunicationLogs = Generated.adminCommunicationLogs;
export const getPlatformCommunicationStats = Generated.adminCommunicationPlatformStats;
export const getPlatformNotificationStats = Generated.adminNotificationsPlatformStats;
export const getCommunicationHealth = Generated.adminCommunicationHealthByHealth;

export const getCommunicationProviders = Generated.adminCommunicationProviders;
export const createCommunicationProvider = Generated.adminCommunicationProvidersPost;
export const updateCommunicationProvider = Generated.adminCommunicationProvidersByProvidersPut;
export const deleteCommunicationProvider = Generated.adminCommunicationProvidersByProvidersDelete;

export const createCommunicationTemplate = Generated.adminCommunicationTemplatesPost;
export const updateCommunicationTemplate = Generated.adminCommunicationTemplatesByTemplatesPut;
export const deleteCommunicationTemplate = Generated.adminCommunicationTemplatesByTemplatesDelete;
export const cloneCommunicationTemplateToLocale =
	Generated.adminCommunicationTemplatesCloneToLocaleByTemplatesPost;

export const publishAnnouncement = Generated.adminAnnouncementsPublishByAnnouncementsPost;
export const unpublishAnnouncement = Generated.adminAnnouncementsUnpublishByAnnouncementsPost;

export const broadcastNotification = Generated.adminNotificationsBroadcastPost;
export const getNotificationsReadReport = Generated.adminNotificationsReadReport;
export const getAllTenants = Generated.adminTenants;
export const getTenantDetail = Generated.adminTenantsByTenants;
export const createTenant = Generated.adminTenantsPost;
export const updateTenant = Generated.adminTenantsByTenantsPut;
export const deleteTenant = Generated.adminTenantsByTenantsDelete;
export const activateTenant = Generated.adminTenantsActivateByTenantsPost;
export const suspendTenant = Generated.adminTenantsSuspendByTenantsPost;
export const getTenantQuota = Generated.adminTenantsQuotaByTenants;
export const updateTenantQuota = Generated.adminTenantsQuotaByTenantsPut;
// U91：走 admin 受众（与 create/update/delete/publish/unpublish 同组），
// 用户面 Generated.announcements 在 admin 平面被 entry-plane 门禁拒 403
export const getAnnouncements = Generated.adminAnnouncements;
export const createAnnouncement = Generated.adminAnnouncementsPost;
export const updateAnnouncement = Generated.adminAnnouncementsByAnnouncementsPut;
export const deleteAnnouncement = Generated.adminAnnouncementsByAnnouncementsDelete;

// Auth Config
export const getAuthConfig = () => Generated.adminSecurityAuthConfig();
export const updateAuthConfig = (data: Record<string, unknown>) =>
	Generated.adminSecurityAuthConfigPut(data);

// Conflict Pairs (SoD)
export const getConflictPairs = Generated.adminRolesConflictPairs;
export const createConflictPair = Generated.adminRolesConflictPairsPost;
export const deleteConflictPair = Generated.adminRolesConflictPairsByConflictPairsDelete;

// Default Roles
export const getDefaultRoles = Generated.adminRolesDefaults;
export const addDefaultRole = Generated.adminRolesDefaultsPost;
export const removeDefaultRole = Generated.adminRolesDefaultsByDefaultsDelete;

// Approval Requests
export const getApprovalRequests = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminApprovalRequests(params);
export const approveApprovalRequest = (id: string, reason?: string, _signal?: AbortSignal) =>
	Generated.adminApprovalRequestsApproveByApprovalRequestsPost(id, { reason: reason ?? '' });
export const rejectApprovalRequest = (id: string, reason: string, _signal?: AbortSignal) =>
	Generated.adminApprovalRequestsRejectByApprovalRequestsPost(id, { reason });

// Batch Operations
export const batchAssignRoles = Generated.adminUsersBatchRolesPost;
export const batchRemoveRoles = Generated.adminUsersBatchRolesDelete;
export const batchAssignPermissions = Generated.adminRolesBatchPermissionsPost;
export const batchRevokePermissions = Generated.adminRolesBatchPermissionsDelete;

// Approval
export const getPendingMembers = (tenantId: string) =>
	Generated.adminTenantsMembersPendingByTenants(tenantId);
export const approveMember = (tenantId: string, memberId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsMembersApproveByTenantsByMembersPost(tenantId, memberId, data);
export const rejectMember = (tenantId: string, memberId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsMembersRejectByTenantsByMembersPost(tenantId, memberId, data);
export const batchApproveMembers = (tenantId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsMembersBatchApproveByTenantsPost(tenantId, data);

// Password Status
export const getPasswordStatus = (userId: string) =>
	Generated.adminUsersPasswordStatusByUsers(userId);

// Status-service endpoints for ops page
export { statusOverview } from '@autional/shared/generated/api';
export const statusMetricsLatency = Generated.statusMetricsLatency;
export const statusMetricsUptime = Generated.statusMetricsUptime;

// Ops — Grafana URLs and topology
const GRAFANA_BASE =
	(typeof window !== 'undefined' && (window as any).__GRAFANA_URL__) ||
	(typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_GRAFANA_URL) ||
	'http://localhost:20300';
export const ops = {
	grafanaOverviewUrl: `${GRAFANA_BASE}/d/authms-overview?kiosk=full`,
	grafanaServicesUrl: (service: string) =>
		`${GRAFANA_BASE}/d/authms-services?var-service=${service}&kiosk=full`,
};

// Profile Service
export const searchProfiles = Generated.adminProfiles;
export const archiveProfile = Generated.adminProfilesArchiveByProfilesPost;
export const exportProfile = Generated.adminProfilesExportByProfiles;
// U316：控制台改接 admin 面（user 面 /profiles/{id} 在 admin 平面被入口平面门禁拒 403；
// admin 双生尚未进 generated，待下轮 swagger 重生成）。
export const getProfile = async (userId: string, _signal?: AbortSignal) => {
	const res = await apiClient.get(`/profile/api/v1/admin/profiles/${userId}`, { signal: _signal });
	return res.data;
};
export const getProfileCompleteness = Generated.profilesCompletenessByProfiles;
export const getProfilePrivacy = Generated.profilesPrivacyByProfiles;
export const getProfilePrivacyImpact = Generated.profilesPrivacyImpactByProfiles;
export const getProfilePublic = Generated.profilesPublicByProfiles;
export const getProfileAvatar = Generated.profileAvatar;

// Invitation Config
export const getInvitationConfig = Generated.adminTenantsInvitationConfigByTenants;
export const updateInvitationConfig = (tenantId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsInvitationConfigByTenantsPut(tenantId, data);

// Quota
export const updateQuota = (tenantId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsQuotaByTenantsPut(tenantId, data);

// App Roles
export const getAppDefaultRoles = (tenantId: string, appId: string) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplications(tenantId, appId);
export const createAppDefaultRole = (
	tenantId: string,
	appId: string,
	data: Record<string, unknown>,
) => Generated.adminTenantsApplicationsRolesByTenantsByApplicationsPost(tenantId, appId, data);
export const updateAppDefaultRole = (
	tenantId: string,
	appId: string,
	roleId: string,
	data: Record<string, unknown>,
) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplicationsByRolesPut(
		tenantId,
		appId,
		roleId,
		data,
	);
export const deleteAppDefaultRole = (tenantId: string, appId: string, roleId: string) =>
	Generated.adminTenantsApplicationsRolesByTenantsByApplicationsByRolesDelete(
		tenantId,
		appId,
		roleId,
	);
export const getAppMembers = (tenantId: string, appId: string, params?: Record<string, unknown>) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplications(tenantId, appId, params);
export const assignAppMember = (tenantId: string, appId: string, data: Record<string, unknown>) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplicationsPost(tenantId, appId, data);
export const revokeAppMember = (tenantId: string, appId: string, roleId: string) =>
	Generated.adminTenantsApplicationsMembersByTenantsByApplicationsByMembersDelete(
		tenantId,
		appId,
		roleId,
	);

// Status Service
export const getIncidents = Generated.statusIncidents;
export const getIncident = Generated.statusIncidentsByIncidents;
export const createIncident = Generated.statusIncidentsPost;
export const updateIncident = Generated.statusIncidentsByIncidentsPut;
export const deleteIncident = (id: string) => Generated.statusIncidentsByIncidentsDelete(id);
export const addIncidentUpdate = Generated.statusIncidentsUpdatesByIncidentsPost;
export const getMaintenances = Generated.statusMaintenances;
export const getMaintenance = Generated.statusMaintenancesByMaintenances;
export const createMaintenance = Generated.statusMaintenancesPost;
export const updateMaintenance = (id: string, data: Record<string, unknown>) =>
	Generated.statusMaintenancesByMaintenancesPut(id, data);
export const deleteMaintenance = (id: string) =>
	Generated.statusMaintenancesByMaintenancesDelete(id);
export const getOverview = Generated.statusOverview;

export const getSubscribers = (params?: Record<string, unknown>) =>
	Generated.statusSubscriptions(params);

// Secret Service — Key Management
export const getSecrets = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminSecrets(params);
export const getSecretDetail = (params?: { key: string }, _signal?: AbortSignal) =>
	Generated.adminSecretsDetail(params);
export const createSecret = (
	data: { key: string; value: string; description?: string },
	_signal?: AbortSignal,
) => Generated.adminSecretsPost(data as any);
export const updateSecret = (
	data: Record<string, unknown>,
	params?: { key: string },
	_signal?: AbortSignal,
) => Generated.adminSecretsUpdatePost(data, params);
export const deleteSecret = (key: string, _signal?: AbortSignal) =>
	// 根因修复 (2026-08-13): 生成 TS 重新生成后函数名从 adminSecretsItemByItemDelete
	// 变为 adminSecretsItemKeyByKeyDelete（路由 /item/key/{key}）。旧引用在运行时
	// "is not a function" → 删除密钥静默失败。
	Generated.adminSecretsItemKeyByKeyDelete(key);
export const rotateSecret = (
	data: Record<string, unknown>,
	params?: { key: string },
	_signal?: AbortSignal,
) => Generated.adminSecretsRotatePost(data, params);
export const revokeSecret = (params?: { key: string }, _signal?: AbortSignal) =>
	Generated.adminSecretsRevokePost(params);
export const getSecretVersions = (params?: { key: string }, _signal?: AbortSignal) =>
	Generated.adminSecretsVersions(params);
export const getSecretVersionValue = (
	data: Record<string, unknown>,
	params?: { key: string },
	_signal?: AbortSignal,
) => Generated.adminSecretsVersionsValuePost(data, params);
export const batchRevokeSecrets = (keys: string[], _signal?: AbortSignal) =>
	Generated.adminSecretsBatchRevokePost({ keys });
export const batchDeleteSecrets = (keys: string[], _signal?: AbortSignal) =>
	Generated.adminSecretsBatchDeletePost({ keys });
export const getEncryptionKeys = (_signal?: AbortSignal) => Generated.adminSecretsEncryptionKeys();

// Server Logs — Service error logs
export const getServerLogs = (params?: Record<string, unknown>) =>
	Generated.adminAuditServerLogs(params);
export const getServerLogServices = () => Generated.adminAuditServerLogsServices();

// ABAC Policies
export const getAbacPolicies = (params?: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAbacPolicies(params);
export const createAbacPolicy = (data: Record<string, unknown>, _signal?: AbortSignal) =>
	Generated.adminAbacPoliciesPost(data);
export const getAbacPolicy = (id: string, _signal?: AbortSignal) =>
	Generated.adminAbacPoliciesByAbacPolicies(id);
export const updateAbacPolicy = (
	id: string,
	data: Record<string, unknown>,
	_signal?: AbortSignal,
) => Generated.adminAbacPoliciesByAbacPoliciesPut(id, data);
export const deleteAbacPolicy = (id: string, _signal?: AbortSignal) =>
	Generated.adminAbacPoliciesByAbacPoliciesDelete(id);

// FeatureGates — Per-tenant feature flags enabled by subscription plan
export const getFeatureGates = () => Generated.adminBillingFeatureGates();

// FeatureGate Tenant Overrides
export const getFeatureGateOverrides = () => Generated.adminBillingFeatureGatesOverrides();

export const upsertFeatureGateOverride = (gateKey: string, enabled: boolean) =>
	Generated.adminBillingFeatureGatesOverridesPut({ gate_key: gateKey, enabled });

// FeatureGate Plan (admin)
export const patchPlanFeatureGates = (planId: string, featureGates: Record<string, unknown>[]) =>
	Generated.adminBillingPlansFeatureGatesByPlansPatch(planId, { feature_gates: featureGates });

// PIM/JIT Role Activations
export const getRoleActivations = (params?: Record<string, unknown>) =>
	Generated.adminRoleActivations(params);
export const approveActivation = (id: string, _reason: string) =>
	Generated.adminRoleActivationsApproveByRoleActivationsPost(id);
export const revokeActivation = (id: string, reason: string) =>
	Generated.adminRoleActivationsRevokeByRoleActivationsPost(id, { reason });

// Reverse Lookup: "Who has this role" / "Who has this permission"
export const getRoleUsers = Generated.adminRolesUsersByRoles;
export const getPermissionUsers = Generated.adminPermissionsUsersByPermissions;
export const getPermissionRoles = Generated.adminPermissionsRolesByPermissions;

export const getRoleChildren = Generated.adminRolesChildrenByRoles;
export const addRoleChild = Generated.adminRolesChildrenByRolesPost;
export const removeRoleChild = Generated.adminRolesChildrenByRolesByChildrenDelete;
export const getRoleParents = Generated.adminRolesParentsByRoles;
export const getRoleEffectivePermissions = Generated.adminRolesEffectivePermissionsByRoles;
export const cloneRole = Generated.adminRolesCloneByRolesPost;
export const requestApproval = Generated.adminRolesApprovalRequestsByRolesPost;

export const assignUserPermissions = Generated.adminUsersPermissionsByUsersPost;
export const revokeUserPermissions = Generated.adminUsersPermissionsByUsersDelete;

// Permission Simulate
export const simulatePermission = Generated.adminPermissionsSimulatePost;

// Risk Config (Phase 3)
export const getRiskConfig = Generated.adminSecurityRiskConfig;
export const updateRiskConfig = Generated.adminSecurityRiskConfigPut;
export const resetRiskConfig = Generated.adminSecurityRiskConfigResetPost;

// Risk Dashboard (Phase 4)
export const getRiskDashboard = Generated.adminSecurityRiskDashboard;

// ============ OAuth Clients (developer-portal merge) ============
export const getOAuthClients = Generated.adminOauthClients;
export const createOAuthClient = Generated.adminOauthClientsPost;
export const getOAuthClient = Generated.adminOauthClientsByClients;
export const updateOAuthClient = Generated.adminOauthClientsByClientsPut;
export const deleteOAuthClient = Generated.adminOauthClientsByClientsDelete;
export const rotateOAuthClientSecret = Generated.adminOauthClientsRotateSecretByClientsPost;
export const getOAuthClientSecrets = Generated.adminOauthClientsSecretsByClients;
export const createOAuthClientSecret = Generated.adminOauthClientsSecretsByClientsPost;
export const deleteOAuthClientSecret = Generated.adminOauthClientsSecretsByClientsBySecretsDelete;
export const deactivateOAuthClientSecret =
	Generated.adminOauthClientsSecretsDeactivateByClientsBySecretsPut;
export const getOAuthClientStats = Generated.adminOauthClientsStatsByClients;

// ============ API Keys (developer-portal merge) ============
export const getApiKeys = Generated.authApiKeys;
export const createApiKey = Generated.authApiKeysPost;
export const getApiKey = Generated.authApiKeysByApiKeys;
export const deleteApiKey = Generated.authApiKeysByApiKeysDelete;
export const rotateApiKey = Generated.authApiKeysRotateByApiKeysPost;
export const updateApiKeyScopes = Generated.authApiKeysScopesByApiKeysPut;
export const updateApiKeyStatus = Generated.authApiKeysStatusByApiKeysPut;

// ============ My Audit Logs (developer-portal merge) ============
export const getMyAuditLogs = Generated.authMeAuditLogs;

// ============ Usage Stats (developer-portal merge) ============
// 无 admin 双生端点，且当前无页面消费（U316 扫描遗留）
export const getAppUsageStats = Generated.billingUsageAppsCurrentByUsageByApps;
// U316：usage 页改接 admin 面
export const getUsageTimeline = Generated.adminBillingUsageTimelineByUsage;
export const getUsageEndpoints = Generated.adminBillingUsageEndpointsByUsage;

// ============ My Devices (developer-portal merge) ============
export const getMyDevices = Generated.authMeDevices;
export const removeMyDevice = Generated.authMeDevicesByDevicesDelete;
export const trustMyDevice = Generated.authMeDevicesTrustByDevicesPut;

// ============ My Sessions (developer-portal merge) ============
export const getMySessions = Generated.authMeSessions;
export const deleteMySessions = Generated.authMeSessionsDelete;
export const deleteMySession = Generated.authMeSessionsBySessionsDelete;

// ============ MFA (developer-portal merge) ============
export const getMfaStatus = Generated.mfaStatusByStatus;
export const enableTotp = Generated.mfaTotpEnablePost;
export const verifyTotp = Generated.mfaTotpVerifyPost;
export const disableTotp = Generated.mfaTotpDisablePost;
export const generateBackupCodes = Generated.mfaBackupCodesGeneratePost;

// ============ Profile (developer-portal merge) ============
export const uploadAvatar = Generated.profilesAvatarUploadByProfilesPost;

// ============ Settings 自助三通道（W2-04 / A-437 · Q-06）============
// 别名增补（生成物已含 self 通道函数；settings 页统一从本文件取接口以避免散落引用）。
// 旧缺陷：保存资料走 admin 端点 updateUser（恒含非空 email → 61002205 必败）；正确通道 = 以下 self 面。
export const updateMyProfile = Generated.authMePut; // PUT /identity/api/v1/auth/me（username）
export const requestEmailChange = Generated.authMeEmailChangePost; // POST .../auth/me/email/change
export const verifyEmailChange = Generated.authMeEmailVerifyPost; // POST .../auth/me/email/verify
export const cancelEmailChange = Generated.authMeEmailChangeCancelPost; // POST .../auth/me/email/change/cancel
export const updateMyAvatar = Generated.profilesAvatarByProfilesPut; // PUT /profile/api/v1/profiles/{user_id}/avatar
